---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS,Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS","Rocky"]

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache,php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache,php for CentOS,Rocky servers
    tags: apache,centos,rocky,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS","Rocky"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS,Rocky)
    tags: centos,rocky,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS","Rocky"]

  - name: install mariadb package (Ubuntu)
    tags: centos,rocky,mariadb
    apt:
      name: mariadb-client-core
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

