---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS,Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS","Rocky"]

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache,php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache,php for CentOS,Rocky servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS","Rocky"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS,Rocky)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS","Rocky"]

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-client-core
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

